name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Build Project
        uses: threeal/cmake-action@v2.0.0

      - name: run test
        run: |
          ./median-validate netlists/s_9_1.cha
          ./median-validate netlists/s_9_8.cha