

const char vhdl_preamble[] = "library IEEE;\n"
"use IEEE.std_logic_1164.all;\n"
"\n"
"package filter_pack is\n"
"  type tkernel is array (NATURAL range <>, NATURAL range <>) of std_logic;\n"
"--  type tkernel is array (NATURAL range <>) of std_logic_vector; --2008\n"
"end filter_pack;\n"
"\n"
"library IEEE;\n"
"use IEEE.std_logic_1164.all;\n"
"use IEEE.std_logic_unsigned.all;\n"
"use IEEE.std_logic_arith.all;\n"
"\n"
"entity med_swp is\n"
"   generic(\n"
"      DATA_WIDTH  : integer\n"
"   );\n"
"   port(\n"
"      RESET : in std_logic;\n"
"      CLK   : in std_logic;\n"
"\n"
"      X     : in std_logic_vector(DATA_WIDTH-1 downto 0);\n"
"      Y     : in std_logic_vector(DATA_WIDTH-1 downto 0);\n"
"\n"
"      MIN    : out std_logic_vector(DATA_WIDTH-1 downto 0);\n"
"      MAX    : out std_logic_vector(DATA_WIDTH-1 downto 0)\n"
"   );\n"
"end entity med_swp;\n"
"\n"
"architecture behavioral of med_swp is\n"
"signal mmin : std_logic_vector(DATA_WIDTH-1 downto 0);\n"
"signal mmax : std_logic_vector(DATA_WIDTH-1 downto 0);\n"
"begin\n"
"\n"
"-- max, min process\n"
"process(X, Y)\n"
"begin\n"
"   if (X > Y) then\n"
"      mmax <= X;\n"
"      mmin <= Y;\n"
"   else\n"
"      mmax <= Y;\n"
"      mmin <= X;\n"
"   end if;\n"
"end process;\n"
"\n"
"process(RESET, CLK)\n"
"begin\n"
"   if (RESET = '1') then\n"
"   elsif (CLK'event AND CLK = '1') then\n"
"      MAX <= mmax;\n"
"      MIN <= mmin;\n"
"   end if;\n"
"end process;\n"
"\n"
"end architecture behavioral; \n"
"\n"
"library IEEE;\n"
"use IEEE.std_logic_1164.all;\n"
"\n"
"entity reg is\n"
"   generic(\n"
"      DATA_WIDTH  : integer\n"
"   );\n"
"   port(\n"
"      RESET : in std_logic;\n"
"      CLK   : in std_logic;\n"
"\n"
"      X     : in std_logic_vector(DATA_WIDTH-1 downto 0);\n"
"      Q     : out std_logic_vector(DATA_WIDTH-1 downto 0)\n"
"   );\n"
"end entity reg;\n"
"\n"
"architecture behavioral of reg is\n"
"begin\n"
"\n"
"process(CLK)\n"
"begin\n"
"   if (CLK'event AND CLK = '1') then\n"
"      Q <= X;\n"
"   end if;\n"
"end process;\n"
"\n"
"end architecture behavioral;\n"
"\n"
"\n"
"library ieee;\n"
"use ieee.std_logic_1164.all;\n"
"use work.filter_pack.all;\n"
"\n"
"library ieee;\n"
"use ieee.std_logic_1164.all;\n"
"use ieee.std_logic_arith.all;\n"
"use ieee.std_logic_unsigned.all;\n"
"use work.filter_pack.all;\n"
"\n";